apiVersion: v1
data:
  nginx-dashboard.json: '{"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana
    --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations
    & Alerts","type":"dashboard"}]},"description":"Show stats from the hnlq715/nginx-vts-exporter.","editable":true,"gnetId":2949,"graphTooltip":0,"id":13,"iteration":1563190344493,"links":[],"panels":[{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":24,"x":0,"y":0},"id":7,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(nginx_upstream_responseMsec{service=~\"$service\"})
    by (backend)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{
    backend }}","metric":"nginx_upstream_response","refId":"A","step":120}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Upstream
    Backend Response","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":12,"x":0,"y":7},"id":1,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_server_connections{service=\"$service\"}[5m]))
    by (status)","format":"time_series","intervalFactor":2,"legendFormat":"{{status}}","refId":"B"}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Server
    Connections","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":12,"x":12,"y":7},"id":4,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_server_cache{service=~\"$service\"}[5m]))
    by (status)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{
    status }}","metric":"nginx_server_cache","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Server
    Cache","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":"0","show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":12,"x":0,"y":14},"id":3,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_server_requests{service=~\"$service\",
    code!=\"total\"}[5m])) by (code)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{
    code }}","metric":"nginx_server_requests","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Server
    Requests","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":12,"x":12,"y":14},"id":2,"legend":{"alignAsTable":false,"avg":false,"current":false,"max":false,"min":false,"rightSide":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_server_bytes{service=~\"$service\",
    host=~\"$upstream\"}[5m])) by (direction, host)","format":"time_series","intervalFactor":2,"legendFormat":"{{host}}
    - {{ direction }}","metric":"nginx_server_bytes","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Server
    Bytes","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"bytes","label":null,"logBase":1,"max":null,"min":"0","show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","description":"This
    one is providing aggregated error codes, but it''s still possible to graph these
    per upstream.","fill":1,"gridPos":{"h":7,"w":12,"x":0,"y":21},"id":6,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_upstream_requests{service=~\"$service\",
    code!=\"total\"}[5m])) by (code)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{
    code }}","metric":"nginx_upstream_requests","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Upstream
    Requests","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}},{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":"Prometheus","fill":1,"gridPos":{"h":7,"w":12,"x":12,"y":21},"id":5,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"links":[],"nullPointMode":"null","paceLength":10,"percentage":false,"pointradius":5,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(irate(nginx_upstream_bytes{service=~\"$service\"}[5m]))
    by (direction)","format":"time_series","interval":"","intervalFactor":2,"legendFormat":"{{
    direction }}","metric":"nginx_upstream_bytes","refId":"A","step":240}],"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Upstream
    Bytes","tooltip":{"msResolution":false,"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}}],"schemaVersion":18,"style":"dark","tags":["prometheus","nginx"],"templating":{"list":[{"allValue":".+","current":{"tags":[],"text":"prod-nginx","value":"prod-nginx"},"datasource":"Prometheus","definition":"label_values(nginx_server_bytes,
    service)","hide":0,"includeAll":true,"label":"Service","multi":false,"name":"service","options":[],"query":"label_values(nginx_server_bytes,
    service)","refresh":1,"regex":"","skipUrlSync":false,"sort":0,"tagValuesQuery":"","tags":[],"tagsQuery":"","type":"query","useTags":false},{"allValue":".+","current":{"text":"www.videoland.com","value":"www.videoland.com"},"datasource":"Prometheus","definition":"label_values(nginx_server_cache{service=~\"$service\"},
    host)","hide":0,"includeAll":true,"label":"Upstream","multi":false,"name":"upstream","options":[],"query":"label_values(nginx_server_cache{service=~\"$service\"},
    host)","refresh":1,"regex":"/(.*com)/","skipUrlSync":false,"sort":0,"tagValuesQuery":"","tags":[],"tagsQuery":"","type":"query","useTags":false}]},"time":{"from":"now-3h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"time_options":["5m","15m","1h","6h","12h","24h","2d","7d","30d"]},"timezone":"browser","title":"NGiNX
    Dashboard","uid":"wMFpbFSWz","version":5}'
kind: ConfigMap
metadata:
  name: nginx-dashboard
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    chart: grafana-3.7.3
    heritage: Tiller
    release: monitoring
  name: monitoring-grafana
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: monitoring
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  grafana.ini: |
    [auth.ldap]
    enabled = true
    config_file = /etc/grafana/ldap.toml
    allow_sign_up = true
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    filters = ldap:debug
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
kind: ConfigMap
metadata:
  labels:
    app: grafana
    chart: grafana-3.7.3
    heritage: Tiller
    release: monitoring
  name: monitoring-grafana
  namespace: monitoring
---
apiVersion: v1
data:
  admin-password: cHJvbS1vcGVyYXRvcg==
  admin-user: YWRtaW4=
  ldap-toml: ldap_config_encrypted_here
kind: Secret
metadata:
  labels:
    app: grafana
    chart: grafana-3.7.3
    heritage: Tiller
    release: monitoring
  name: monitoring-grafana
  namespace: monitoring
type: Opaque