{
 "title": "NGiNX Dashboard",
 "description": "Show stats from the hnlq715/nginx-vts-exporter.",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_server_bytes, service)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_server_cache{service=~\"$service\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_responseMsec{service=~\"$service\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_connections{service=\"$service\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Server Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_cache{service=~\"$service\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{service=~\"$service\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_bytes{service=~\"$service\", host=~\"$upstream\"}[5m])) by (direction, host)",
     "legendFormat": "{{host}} - {{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_requests{service=~\"$service\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_bytes{service=~\"$service\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}